---
- hosts: Test-server
  become: true
  tasks:
    - name: Configure pending packages
      become: yes
      command: dpkg --configure -a

    - name: update apt
      command: sudo apt-get update

    - name: install docker
      command: sudo apt install -y docker.io

    - name: start docker service
      command: sudo systemctl start docker

    - name: deploy insureme application
      command: sudo docker run -itd -p 8081:8081 shubhamkushwah123/insure-me:1.0
      
    - name: Copy final-project.jar to remote host
      copy:
        src: final-project.jar
        dest: /home/ubuntu/final-project.jar
        owner: ubuntu
        group: ubuntu
        mode: '0644'


